#!/usr/bin/env python3
"""sm → iTerm2 bridge.

Listens for sm's custom control sequences (OSC 1337 Custom=id=sm:<base64>)
and opens a native iTerm2 window running the agent: over ssh it dials back
into the host, and for a local sm (empty host) it types the command straight
into a fresh local shell. Terminal output is untrusted input: every payload
field is validated against a strict pattern before anything runs (the host
must start with an alphanumeric and ssh gets an explicit `--` end-of-options
marker, so a host can never be parsed as a flag; the PATH-prepend hint is
honored only for the ssh form). The only command shapes ever executed are a
`cd`+`tmux`+`claude|codex` line — locally, or via `ssh -t -- <host>`.

Install: ~/Library/Application Support/iTerm2/Scripts/AutoLaunch/ and enable
Settings → General → Magic → "Enable Python API".
"""
import base64
import json
import re
import shlex

import iterm2
import iterm2.api_pb2
import iterm2.rpc

HOST_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._@-]{0,127}$")
NAME_RE = re.compile(r"^sm(-[a-z0-9]+)+$")
AGENTS = ("claude", "codex")
ID_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,255}")
BINDIR_RE = re.compile(r"^/[A-Za-z0-9._@/-]{0,512}$")

# dedupe key -> iTerm2 window id of the window still (presumably) showing it
windows = {}


def agent_argv_ok(argv):
    """Accept only the new/resume command shapes generated by sm."""
    if not isinstance(argv, list) or not all(isinstance(a, str) for a in argv):
        return False
    if len(argv) not in (1, 3) or argv[0] not in AGENTS:
        return False
    if len(argv) == 1:
        return True
    return bool(ID_RE.fullmatch(argv[2])) and (
        (argv[0] == "claude" and argv[1] == "--resume") or
        (argv[0] == "codex" and argv[1] == "resume"))


def remote_command(spec):
    """Build the validated command, or None to reject the payload.

    An empty host means sm runs on THIS machine (no ssh involved): the
    command is typed directly into the new window's local shell.
    """
    rejected = (None, None, None)
    if not isinstance(spec, dict):
        return rejected
    for field in ("host", "name", "dir", "bindir", "window_key"):
        if not isinstance(spec.get(field, ""), str):
            return rejected
    for field in ("attach", "tmux"):
        if not isinstance(spec.get(field, False), bool):
            return rejected
    host = spec.get("host", "")
    name = spec.get("name", "")
    dir_ = spec.get("dir", "")
    bindir = spec.get("bindir", "")
    window_key = spec.get("window_key", "")
    argv = spec.get("argv", [])
    if not isinstance(argv, list) or not all(isinstance(a, str) for a in argv):
        return rejected
    if host and not HOST_RE.fullmatch(host):
        return rejected
    if name and not NAME_RE.fullmatch(name):
        return rejected
    if window_key and not NAME_RE.fullmatch(window_key):
        return rejected
    if bindir and not BINDIR_RE.fullmatch(bindir):
        return rejected
    # Quoting does not protect the live shell's line editor from control bytes.
    if any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in dir_):
        return rejected
    if spec.get("attach"):
        if not NAME_RE.fullmatch(name) or argv or spec.get("tmux"):
            return rejected
        # Hard single quotes, not shlex.quote: "=" is in shlex's safe set,
        # but an unquoted =word triggers zsh's equals expansion remotely.
        return host, host + "|" + (window_key or name), "exec tmux attach-session -t '=" + name + "'"
    if not agent_argv_ok(argv):
        return rejected
    inner = " ".join(shlex.quote(a) for a in argv)
    # The remote end of a fresh ssh runs with sshd's bare PATH, and tmux
    # panes it creates inherit that PATH — the agent would be "command not
    # found". sm resolves the agent's directory in the user's real
    # environment and sends it as bindir; prepend it remotely. LOCAL
    # execution deliberately ignores bindir: a fresh local shell already has
    # the user's normal PATH, and honoring a forged bindir here would let
    # terminal output steer which local binary "claude" resolves to.
    path = ""
    if bindir and host:
        path = "export PATH=" + shlex.quote(bindir) + ':"$PATH" && '
    if spec.get("tmux"):
        if not NAME_RE.fullmatch(name):
            return None, None, None
        cmd = "{p}cd {d} && exec tmux new-session -A -s {n} -c {d} {i}".format(
            p=path, d=shlex.quote(dir_), n=shlex.quote(name), i=inner)
    else:
        cmd = "{p}cd {d} && exec {i}".format(p=path, d=shlex.quote(dir_), i=inner)
    # Dedupe key: tracked launches have a unique tmux name; untracked ones
    # must include dir, or every untracked "new session" (bare agent argv)
    # would collide on one window across all projects.
    # host joins the dedupe key so a local and a remote launch with the same
    # tmux name (or dir+argv) never focus each other's window.
    return host, host + "|" + (window_key or name or (dir_ + " " + inner)), cmd


# The three calls below go straight to iTerm2's RPCs instead of through the
# iterm2 module's Window/Session objects. Those objects mirror the app state
# through notifications, and that mirror lags: with the module bundled with
# iTerm2 3.7 (iterm2 2.22) the focus notification for a brand-new window is
# dropped while the creation-triggered refresh is in flight, so
# Window.current_tab stayed None for about a second and every launch after
# the first found "no session" to type into — the window opened and sat at
# a bare prompt. The RPC replies carry the ids directly and answer for the
# window that exists right now, not for a cached picture of it.


async def open_window(connection):
    """Open a plain shell window (default profile).

    Returns (window_id, session_id), or None after logging the failure.
    """
    reply = (await iterm2.rpc.async_create_tab(connection)).create_tab_response
    status = iterm2.api_pb2.CreateTabResponse.Status
    if reply.status != status.Value("OK"):
        print("[sm] window creation failed:", status.Name(reply.status))
        return None
    return reply.window_id, reply.session_id


async def type_into(connection, session_id, text):
    """Send text to session_id as if typed; logs (does not raise) on failure."""
    reply = (await iterm2.rpc.async_send_text(
        connection, session_id, text, False)).send_text_response
    status = iterm2.api_pb2.SendTextResponse.Status
    if reply.status != status.Value("OK"):
        print("[sm] typing into session", session_id, "failed:", status.Name(reply.status))


async def refocus(connection, window_id):
    """Bring window_id to the front. False when iTerm2 no longer has it —
    the authoritative check that keeps a closed window from eating every
    relaunch of the same session."""
    reply = (await iterm2.rpc.async_activate(
        connection, False, False, True, window_id=window_id)).activate_response
    return reply.status == iterm2.api_pb2.ActivateResponse.Status.Value("OK")


async def handle(connection, payload):
    spec = json.loads(base64.b64decode(payload))
    print("[sm] payload:", json.dumps(spec, sort_keys=True))
    host, key, cmd = remote_command(spec)
    if not cmd:
        print("[sm] rejected by validation")
        return
    old = windows.get(key)
    if old is not None:
        if await refocus(connection, old):
            print("[sm] focused existing window for", key)
            return
        print("[sm] window for", key, "is gone; opening a new one")
        windows.pop(key, None)
    if host:
        # An explicit launch must not inherit a login RemoteCommand or try
        # to rebind forwards already owned by the original SSH connection.
        line = "ssh -t -o RemoteCommand=none -o ClearAllForwardings=yes -- {h} {c}".format(
            h=shlex.quote(host), c=shlex.quote(cmd))
    else:
        line = cmd  # local sm: run directly in the new window's shell
    print("[sm] running:", line)
    # Open a plain shell window and type the command into it: the user's own
    # shell does the parsing (not iTerm2's tokenizer) and supplies the usual
    # environment (ssh agent etc.); on failure the window stays open showing
    # the error instead of flashing closed. The leading space keeps it out of
    # histories configured with HIST_IGNORE_SPACE.
    opened = await open_window(connection)
    if opened is None:
        return
    window_id, session_id = opened
    await type_into(connection, session_id, " " + line + "\n")
    windows[key] = window_id


async def main(connection):
    print("[sm] bridge listening (identity 'sm')")
    async with iterm2.CustomControlSequenceMonitor(
            connection, "sm", r"^(.+)$") as mon:
        while True:
            match = await mon.async_get()
            try:
                await handle(connection, match.group(1))
            except Exception as e:
                print("[sm] dropped payload:", e)  # never kill the listener


iterm2.run_forever(main)
